os:
  - osx
  - linux

before_install:
  - test -n $CC && unset CC

#install: make ninja cmake get-deps

compiler:
  - gcc
  - clang

language: cpp
# language:
#   - c
#   - cpp

stages:
  - compile
  - build
  - test
  - deploy
  - name: deploy2
    if: branch = deploy


jobs:
  include:
    - stage: build
      script: mkdir build && cd build && cmake .. && make
    - stage: test
      script: cd build && ctest
