os: linux
# os:
#   - osx
#   - linux

#before_install:
#  - test -n $CC && unset CC
#install: make ninja cmake get-deps

# compiler: gcc
compiler:
  - gcc
  - clang

language: cpp
# language:
#   - c
#   - cpp
#   - shell
#   - sh
#   - bash
#   - minimal
#   - generic

script: skip

stages:
#   - compile
#   - build
  - test
#   - deploy
#   - name: deploy2
#     if: branch = deploy

jobs:
  include:
#     - stage: build
#       language: generic
#       install: skip
#       script: mkdir build && cd build && cmake .. && make && cd ..
    - stage: test
      script:
        - mkdir build && cd build
        - cmake .. && make
        - ctest
        - cd ..
